package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
	"sistema-editorial/editora/backend/src/logistica/entity"
)

type SettingsRepository struct {
	pool *pgxpool.Pool
}

func NewSettingsRepository(pool *pgxpool.Pool) *SettingsRepository {
	return &SettingsRepository{pool: pool}
}

func (r *SettingsRepository) Get(ctx context.Context) (entity.SettingsRecord, error) {
	const sql = `
		SELECT
			provider_padrao,
			timeout_segundos,
			coalesce(email_contato, ''),
			origem_nome,
			coalesce(origem_cep, ''),
			coalesce(origem_endereco, ''),
			coalesce(origem_numero, ''),
			coalesce(origem_bairro, ''),
			coalesce(origem_cidade, ''),
			coalesce(origem_uf, ''),
			melhor_envio_habilitado,
			melhor_envio_sandbox,
			coalesce(melhor_envio_base_url, ''),
			coalesce(melhor_envio_access_token, ''),
			coalesce(melhor_envio_refresh_token, ''),
			coalesce(melhor_envio_client_id, ''),
			coalesce(melhor_envio_client_secret, ''),
			coalesce(melhor_envio_redirect_url, ''),
			coalesce(melhor_envio_user_agent, ''),
			superfrete_habilitado,
			superfrete_sandbox,
			coalesce(superfrete_base_url, ''),
			coalesce(superfrete_token, ''),
			coalesce(superfrete_user_agent, ''),
			coalesce(superfrete_servicos, ''),
			loggi_habilitado,
			loggi_sandbox,
			coalesce(loggi_base_url, ''),
			coalesce(loggi_company_id, ''),
			coalesce(loggi_client_id, ''),
			coalesce(loggi_client_secret, ''),
			coalesce(loggi_pickup_type, ''),
			coalesce(loggi_external_service_id, ''),
			frenet_habilitado,
			frenet_sandbox,
			coalesce(frenet_base_url, ''),
			coalesce(frenet_token, ''),
			coalesce(frenet_platform, ''),
			coalesce(frenet_platform_versao, ''),
			criado_em,
			atualizado_em
		FROM logistica_configuracoes
		WHERE id = 1
	`

	var record entity.SettingsRecord
	err := r.pool.QueryRow(ctx, sql).Scan(
		&record.DefaultProvider,
		&record.TimeoutSeconds,
		&record.ContactEmail,
		&record.Origin.Name,
		&record.Origin.CEP,
		&record.Origin.Address,
		&record.Origin.Number,
		&record.Origin.District,
		&record.Origin.City,
		&record.Origin.State,
		&record.MelhorEnvioEnabled,
		&record.MelhorEnvio.Sandbox,
		&record.MelhorEnvio.BaseURL,
		&record.MelhorEnvio.AccessToken,
		&record.MelhorEnvio.RefreshToken,
		&record.MelhorEnvio.ClientID,
		&record.MelhorEnvio.ClientSecret,
		&record.MelhorEnvio.RedirectURL,
		&record.MelhorEnvio.UserAgent,
		&record.SuperFreteEnabled,
		&record.SuperFrete.Sandbox,
		&record.SuperFrete.BaseURL,
		&record.SuperFrete.Token,
		&record.SuperFrete.UserAgent,
		&record.SuperFrete.Services,
		&record.LoggiEnabled,
		&record.Loggi.Sandbox,
		&record.Loggi.BaseURL,
		&record.Loggi.CompanyID,
		&record.Loggi.ClientID,
		&record.Loggi.ClientSecret,
		&record.Loggi.PickupType,
		&record.Loggi.ExternalServiceID,
		&record.FrenetEnabled,
		&record.Frenet.Sandbox,
		&record.Frenet.BaseURL,
		&record.Frenet.Token,
		&record.Frenet.Platform,
		&record.Frenet.PlatformVer,
		&record.CreatedAt,
		&record.UpdatedAt,
	)
	return record, err
}

func (r *SettingsRepository) Upsert(ctx context.Context, input entity.SettingsRecord) error {
	const sql = `
		INSERT INTO logistica_configuracoes (
			id,
			provider_padrao,
			timeout_segundos,
			email_contato,
			origem_nome,
			origem_cep,
			origem_endereco,
			origem_numero,
			origem_bairro,
			origem_cidade,
			origem_uf,
			melhor_envio_habilitado,
			melhor_envio_sandbox,
			melhor_envio_base_url,
			melhor_envio_access_token,
			melhor_envio_refresh_token,
			melhor_envio_client_id,
			melhor_envio_client_secret,
			melhor_envio_redirect_url,
			melhor_envio_user_agent,
			superfrete_habilitado,
			superfrete_sandbox,
			superfrete_base_url,
			superfrete_token,
			superfrete_user_agent,
			superfrete_servicos,
			loggi_habilitado,
			loggi_sandbox,
			loggi_base_url,
			loggi_company_id,
			loggi_client_id,
			loggi_client_secret,
			loggi_pickup_type,
			loggi_external_service_id,
			frenet_habilitado,
			frenet_sandbox,
			frenet_base_url,
			frenet_token,
			frenet_platform,
			frenet_platform_versao,
			atualizado_em
		)
		VALUES (
			1,
			$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
			$11,$12,$13,$14,$15,$16,$17,$18,$19,
			$20,$21,$22,$23,$24,$25,
			$26,$27,$28,$29,$30,$31,$32,$33,
			$34,$35,$36,$37,$38,$39,
			NOW()
		)
		ON CONFLICT (id) DO UPDATE SET
			provider_padrao = EXCLUDED.provider_padrao,
			timeout_segundos = EXCLUDED.timeout_segundos,
			email_contato = EXCLUDED.email_contato,
			origem_nome = EXCLUDED.origem_nome,
			origem_cep = EXCLUDED.origem_cep,
			origem_endereco = EXCLUDED.origem_endereco,
			origem_numero = EXCLUDED.origem_numero,
			origem_bairro = EXCLUDED.origem_bairro,
			origem_cidade = EXCLUDED.origem_cidade,
			origem_uf = EXCLUDED.origem_uf,
			melhor_envio_habilitado = EXCLUDED.melhor_envio_habilitado,
			melhor_envio_sandbox = EXCLUDED.melhor_envio_sandbox,
			melhor_envio_base_url = EXCLUDED.melhor_envio_base_url,
			melhor_envio_access_token = EXCLUDED.melhor_envio_access_token,
			melhor_envio_refresh_token = EXCLUDED.melhor_envio_refresh_token,
			melhor_envio_client_id = EXCLUDED.melhor_envio_client_id,
			melhor_envio_client_secret = EXCLUDED.melhor_envio_client_secret,
			melhor_envio_redirect_url = EXCLUDED.melhor_envio_redirect_url,
			melhor_envio_user_agent = EXCLUDED.melhor_envio_user_agent,
			superfrete_habilitado = EXCLUDED.superfrete_habilitado,
			superfrete_sandbox = EXCLUDED.superfrete_sandbox,
			superfrete_base_url = EXCLUDED.superfrete_base_url,
			superfrete_token = EXCLUDED.superfrete_token,
			superfrete_user_agent = EXCLUDED.superfrete_user_agent,
			superfrete_servicos = EXCLUDED.superfrete_servicos,
			loggi_habilitado = EXCLUDED.loggi_habilitado,
			loggi_sandbox = EXCLUDED.loggi_sandbox,
			loggi_base_url = EXCLUDED.loggi_base_url,
			loggi_company_id = EXCLUDED.loggi_company_id,
			loggi_client_id = EXCLUDED.loggi_client_id,
			loggi_client_secret = EXCLUDED.loggi_client_secret,
			loggi_pickup_type = EXCLUDED.loggi_pickup_type,
			loggi_external_service_id = EXCLUDED.loggi_external_service_id,
			frenet_habilitado = EXCLUDED.frenet_habilitado,
			frenet_sandbox = EXCLUDED.frenet_sandbox,
			frenet_base_url = EXCLUDED.frenet_base_url,
			frenet_token = EXCLUDED.frenet_token,
			frenet_platform = EXCLUDED.frenet_platform,
			frenet_platform_versao = EXCLUDED.frenet_platform_versao,
			atualizado_em = NOW()
	`

	_, err := r.pool.Exec(
		ctx,
		sql,
		input.DefaultProvider,
		input.TimeoutSeconds,
		input.ContactEmail,
		input.Origin.Name,
		input.Origin.CEP,
		input.Origin.Address,
		input.Origin.Number,
		input.Origin.District,
		input.Origin.City,
		input.Origin.State,
		input.MelhorEnvioEnabled,
		input.MelhorEnvio.Sandbox,
		input.MelhorEnvio.BaseURL,
		input.MelhorEnvio.AccessToken,
		input.MelhorEnvio.RefreshToken,
		input.MelhorEnvio.ClientID,
		input.MelhorEnvio.ClientSecret,
		input.MelhorEnvio.RedirectURL,
		input.MelhorEnvio.UserAgent,
		input.SuperFreteEnabled,
		input.SuperFrete.Sandbox,
		input.SuperFrete.BaseURL,
		input.SuperFrete.Token,
		input.SuperFrete.UserAgent,
		input.SuperFrete.Services,
		input.LoggiEnabled,
		input.Loggi.Sandbox,
		input.Loggi.BaseURL,
		input.Loggi.CompanyID,
		input.Loggi.ClientID,
		input.Loggi.ClientSecret,
		input.Loggi.PickupType,
		input.Loggi.ExternalServiceID,
		input.FrenetEnabled,
		input.Frenet.Sandbox,
		input.Frenet.BaseURL,
		input.Frenet.Token,
		input.Frenet.Platform,
		input.Frenet.PlatformVer,
	)
	return err
}
